### ISSUE TITLE
Survey dog watching service

### ISSUE THREAD

**Issue by leo-le-07** [middle-guys/iflight#5]
Acceptance test
- [x] Survey about this project
- [x] Write result of the survey to GitHub
  Note:
- at least 3 different people for feedback

**Comment by hongtran** [comment]
Link form survey
https://docs.google.com/forms/d/1ZUnMGSLb4FsSD277wMp2JGfskrFDZpXaawkjS9igPUg/edit

**Comment by hongtran** [comment]
How many time do you go by plane in a year ?
< 3 times/ year (50%)
3 - 6 times/ year (36.4%)
6 - 9 times / year (13.6%)
never 
other
How did you booking ticket airlines ?
Booking on their website (50%)
Via agency booking ticket airlines(27.3%)
Via website finding cheap ticket(18.2%)
other(4.5%)
Are you interested in the promotion or cheap tickets ?
Usually (31.8%)
Sometime(63.6%)
Rarely (4.1%)
other
Do you often searching cheap tickets or visit your family or visit your friends? If yes, you usually do it somehow ?
By the system finding cheap tickets (36.4%)
Go to website (vietnam airline, vietjet, jetstar) to watching and booking cheap tickets(45.5%)
The agency cheap ticket(9.1%)
other(9.1%)
Do you need one person always 24/7 to answer all question relating to flights coming or not.
Yes (81.8%)
No(18.2%)
Do you have any problem when you booking airlines ticket ?
No - 4
Payment - 2
The ticket not clear price, so that waste time for first time book
Dont know whether buy now nor wait more few days to get cheaper ticket
Difficulty in canceling or change ticket or change time
Problem about time
Found ticket with good price before begin about 
- Connection flight waiting time is so long
- Payment online has been charged extra price
- Buying extra luggage doesn’t have guide clearly
So busy, no free time to finding cheap ticket
Hard to find cheap ticket, always buy ticket hight price. The Server time out when a lot of people buy the same time.
So complicated but less infomation
Delay

How old are you ?
20
21
24
25 - 5
26 - 8
27 -2
30
31
33 - 2

**Comment by leo-le-07** [comment]
@hongtran Cool summary report ! Can you format text more beautiful a little bit ?

**Comment by hongtran** [comment]
**The summary result survey, we have 24 responses**

_**How many times do you go by plane per year ?**_
- < 3 times/ year (50%)
- 3 - 6 times/ year (36.4%)
- 6 - 9 times / year (13.6%)

**_How did you usually book your airline tickets ?_**
- Via airline websites (50%)
- Via agencies airline (27.3%)
- Via other website (not the original airline website) (18.2%)
- other(4.5%)

**_Are you interested in the promotion or cheap tickets ?_**
- Usually (31.8%)
- Sometime(63.6%)
- Rarely (4.1%)

**_Do you often search cheap tickets to visit your family or visit your friends? If yes, you usually do it somehow ?_**
- Via websites support finding cheap price ticket (36.4%)
- Go to original airline websites (vietnam airline, vietjet, jetstar) to check and to book in case finding cheap price (45.5%)
- Via agencies (9.1%)
- Other (9.1%)

**_Do you need one person always 24/7 to answer all question relating to flights coming or not._**
- Yes (81.8%)
- No(18.2%)

**_Do you have any problem when you booking airlines ticket ?_**
- No idea (4)
- Payment method (2)
- The ticket price doesn't show including price details, so that waste time for first time book
- Have no idea to buy the ticket now OR wait for next days can get a cheaper one.
- Difficulty in canceling or change ticket or change time
- Time problem ??
- Found good price ticket before 1 or 2 weeks taking off 
- Connection flight waiting time is so long
- Payment online has been charged extra price
- Buying extra luggage doesn’t have guide clearly
- So busy, don't have enough free time to find cheap ticket
- Hard to find cheap ticket, always buy ticket higher one. The server usually die when a lot of people visit at the same time.
- So complicated but less information
- Delay

**_How old are you ?_**
- 20
- 21
- 24
- 25 (5)
- 26  (8)
- 27 (2)
- 30
- 31
- 33 (2)
